### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by sickcodes** [felixrieseberg/macintosh.js#14]
Awesome project, I would love to play with it, do you think you could add a license? GPL would be nice :)

Edit: a license to reuse your code, not the VM!

**Comment by lrenaud** [comment]
Might be worth checking the bottom of the readme.

**From README.md**
> This project is provided for educational purposes only. It is not affiliated with and has not been approved by Apple.

Formalizing the license is likely a minefield given the mix of abandoned legacy software, electron bundling, and private work.

**Comment by sickcodes** [comment]
Good enough for me!

[https://www.copyrightuser.org/understand/exceptions/education/](https://www.copyrightuser.org/understand/exceptions/education/)
