### ISSUE TITLE
Stuck on loading emulator dependencies

### ISSUE THREAD

**Issue by tsebastiani** [felixrieseberg/macintosh.js#15]
![image](https://user-images.githubusercontent.com/15978528/88799174-5c356180-d1a6-11ea-84f2-55030c3e6fe2.png)

The emulator loads up to the point that you can see in the screenshot, but doesn't go further.

Pop_os 20.04 dell XPS 13 2019

**Comment by oliwer** [comment]
Same here on Ubuntu 20.04. And no logs :(

**Comment by HankG** [comment]
This is the same as Issue #4

**Comment by buraksezer** [comment]
This solution worked for me: https://github.com/felixrieseberg/macintosh.js/issues/13#issuecomment-665645801 

Ubuntu 20.04 on ThinkPad E15

**Comment by havanahjoe** [comment]
The solution also worked for me on Pop OS 20.04 on an XPS 15

**Comment by felixrieseberg** [comment]
Thanks friends, I'm moving discussion here: https://github.com/felixrieseberg/macintosh.js/issues/18

(Apologies for the bug!)
