### ISSUE TITLE
Solution: App not booting on Linux, stuck at emulator loading

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/macintosh.js#18]
**As of 1.0.4, this issue is fixed. I just corrected my bug five minutes ago, so if you're running Linux, you might have to re-download macintosh.js: https://github.com/felixrieseberg/macintosh.js/releases/tag/v1.0.4**

Apologies for the issues and thank you for your patience.

**Comment by himdel** [comment]
:+1: with 1.0.2 on Debian, with the chown, there's no longer need to call yarn manually (#4), but it still won't start without `--no-sandbox`:

```
$ macintosh.js 
[934052:0729/161820.766272:FATAL:setuid_sandbox_host.cc(158)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /usr/lib/macintosh.js/chrome-sandbox is owned by root and has mode 4755.
Trace/breakpoint trap (core dumped)
himdel@thror:~$ macintosh.js  --no-sandbox
(works)
```

**Comment by felixrieseberg** [comment]
As of 1.0.4, this issue is fixed. I just corrected my bug five minutes ago, so if you're running Linux, you might have to re-download macintosh.js: https://github.com/felixrieseberg/macintosh.js/releases/tag/v1.0.4

Apologies for the issues and thank you for your patience.
