### ISSUE TITLE
Disk fails to load with /home and / on different partitions

### ISSUE THREAD

**Issue by mcclurgm** [felixrieseberg/macintosh.js#26]
When I try to load macintosh.js, it fails every time with the error 
>Uncaught (in promise) Error: EXDEV: cross-device link not permitted, rename '/home/michael/.config/macintosh.js/disk' -> '/usr/lib/macintosh.js/resources/app/src/basilisk/disk'

As far as I can tell, here's what's happening:
macintosh.js moves/renames/links (or something) the `disk` file from my `~/.config` folder to its spot in `/usr`. On my system, `~` and `/` are in different partitions. This means that it needs to move the file between partitions. Apparently that's not allowed, hence the EXDEV error.

This may be a bit of an edge case, but AFAIK it's somewhat common practice on Linux. I understand if it's not possible/worthwhile to fix this, but it would be nice to be able to run on my system.

**Comment by felixrieseberg** [comment]
Thank you for the report! Truth be told, I made a stupid mistake with my first release of macintosh.js and did not expect it to take off as much as I did.

Could you give https://github.com/felixrieseberg/macintosh.js/releases/tag/v1.0.4 a try? I have a feeling it should fix your issue, but I'd love to know for sure.

**Comment by rjeli** [comment]
FWIW, I'm on buster, and my /home and / are on different partitions:

```
$ df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            7.8G     0  7.8G   0% /dev
tmpfs           1.6G  9.7M  1.6G   1% /run
/dev/nvme0n1p2  197G  163G   24G  88% /
tmpfs           7.9G   52M  7.8G   1% /dev/shm
tmpfs           5.0M  4.0K  5.0M   1% /run/lock
tmpfs           7.9G     0  7.9G   0% /sys/fs/cgroup
/dev/nvme0n1p1  511M   12M  500M   3% /boot/efi
/dev/sda1       1.8T  1.1T  687G  61% /home
tmpfs           1.6G   20K  1.6G   1% /run/user/1000
```

And

- 1.0.1 worked fine for me after `yarn add ..` and `sudo macintosh.js --no-sandbox`
- 1.0.4 works perfectly out of the box.

**Comment by mcclurgm** [comment]
Unfortunately I can't verify anything, since for me the interface bogs down on the loading screen. I think this is unrelated though, so I'd believe @rjeli that it's now working.

**Comment by felixrieseberg** [comment]
Thank you!
