### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by 5E7EN** [felixrieseberg/macintosh.js#28]
dear God save us all

**Comment by mlorentz** [comment]
Why not?

**Comment by MalEbenSo** [comment]
Thank you! Thank you so much. 

I have long looked for a way to re-animate old Macintosh software. And this very much looks like it. 

I have immediately tried out macintosh.js when I read about it, and it just worked. Right away. Thank you. (With all due respects to the developers of Basilisk II and their wonderful work – and I understand, that they have also significantly contributed to this project –, I never _really_ got it to run, just _kind of_.)

Ease of setup is one contribution of macintosh.js over the status quo. 
The other is that of platform independence, both OS and CPU architecture.

The old MacOS is great to study UI concepts and the history of it. Without a live object, many GUIs appear the same except for graphic differences. They are not. Atari and Amiga, GEM Desktop and Windows 286 (and following versions) _feel_ succintly different to the user, although the reasons are subtle. And that can best (or only?) be discovered by interaction with the OS and running applications. 

For these reasons, other versions of MacOS (6.0.7, 7.1, 7.5.3) would be helpful, too.

Projects like this contribute to record the fast-paced and fleeting history of IT. 
So please continue this project. 

I wish Apple (and other IT companies) would support efforts like this in the way that automobile makers support vintage cars, even have elaborate museums to show of their technical history, their company evolvement and genes.

**Comment by greglindquist** [comment]
I see my issue was already logged. Moving on!

**Comment by 5E7EN** [comment]
I'm quite impressed as well. This issue was just to poke fun of the concept since it seemed so abstract until now - but great work. Really. 

Will close to avoid further confusion. Stay safe everyone ❤️
