### ISSUE TITLE
Why is the Windows release in both 64 bit and 32 bit, but Linux is 64 bit only?

### ISSUE THREAD

**Issue by DoctorWho8** [felixrieseberg/macintosh.js#34]
A question:
Why is the Windows release in both 64 bit, and 32 bit, but the Linux one is in 64 bit only? 
And has an attempt to build the source code  in a 32 bit Linux environment been tried?

Oh and if it helps I am a Slackware user myself and versions 13.37 all the way to 14,.2 are available in both.

**Comment by felixrieseberg** [comment]
It probably works just fine, but from what I can tell, the vast majority of Linux users is on 64 bit. I'd take a PR though!
