### ISSUE TITLE
How to transfer files?

### ISSUE THREAD

**Issue by RUvlad1** [felixrieseberg/macintosh.js#39]
I looked at the description of this and it told me to use the Help button at the bottom, I couldn't find one, can someone give me a more detailed guide on how to do this?

**Comment by felixrieseberg** [comment]
It's here:

![image](https://user-images.githubusercontent.com/1426799/88963549-d9231280-d25c-11ea-8b73-cf11e3aabb7e.png)

**Comment by cocopete** [comment]
doesn't work
