### ISSUE TITLE
hypercard?

### ISSUE THREAD

**Issue by humanchimp** [felixrieseberg/macintosh.js#5]
Kudos on this really fun project!

![Screen Shot 2020-07-28 at 14 19 51 ](https://user-images.githubusercontent.com/575266/88723277-6f302f00-d0dd-11ea-91c1-c72dcf978bfc.png)

_Exhibit_: could not find HyperCard 😢 

Having HyperCard (or at least HyperCard Player and a bunch of stacks) would uncork a world of possibilities... Does it seem like it would be worth the lift?

**Comment by darth-cheney** [comment]
I second this. It's available at Macintosh Garden

**Comment by felixrieseberg** [comment]
Generally speaking, here's how you install software:

1) Find your software on pages like Macintosh Garden or Macintosh Repository. Disk images (`iso`, `toast`, `img`) work best.
2) Find the `macintosh.js` directory in your home directory. The `Help` menu in the app can help with creating that folder, but on Windows, it's usually `C:\Users\[username]\macintosh.js`, on macOS and Linux it's in `~/macintosh.js`.
3) Put that disk image into that folder and restart macintosh.js.
4) If everything worked, you'll find your disk image mounted in your virtual Mac.
5) Go and install!

Now, let's talk about HyperCard - I've got a copy [here](https://1drv.ms/u/s!AkfaAw_EaahOk5xa_QI78jx7TsRKxQ?e=cZ53Xn). Link is good for a few days <3

**Comment by jorisw** [comment]
`set userlevel to 5`

**Comment by galtenberg** [comment]
The **Help** menu mentioned is the one at the bottom of the window - see https://github.com/felixrieseberg/macintosh.js/issues/39

I created the ~/macintosh.js/ and ~/macintosh.js/VM folders. 

In the emulator, those directories show up in the Unix mount, but nothing is inside the VM directory there. Still working through it...

**Comment by abulka** [comment]
I also had to create the ~/macintosh.js/ folder manually.

The installed `Hypercard 2.4/` app folder ends up in the root of the `macintosh.js` filesystem, not in `macintosh.js/Applications` where most of the other apps are.

**Comment by jidfjvijiv** [comment]
please help missing user directory
