### ISSUE TITLE
How to install .dsk image?

### ISSUE THREAD

**Issue by steve-scalyr** [felixrieseberg/macintosh.js#51]
Thanks for creating this!

Back in the day, I was one of the authors of Spectre (https://macintoshgarden.org/games/spectre). It's been a long time since I've had any way of accessing the game. It's hosted at the link above, but the download contains a .dsk file. I followed the instructions to load the .dsk file into the emulator, but when I double-click on the file from within the emulator I get "The document ... could not be opened, because the application program that created it could not be found". I've looked for instructions but haven't figured out how to load a .dsk image into macintosh.js. Is it necessary to convert the file to ISO or IMG?

**Comment by felixrieseberg** [comment]
Hey Steve! Thanks for stopping by, I'm honored. You can just rename `dsk` files to `img` files and this app will auto-mount them right away. The real trouble is possibly that there's currently no support for anything but 32 bit video depth...

![image](https://user-images.githubusercontent.com/1426799/89111804-f4ce1a80-d40e-11ea-87ca-3f22bca291f0.png)

**Comment by steve-scalyr** [comment]
Bummer! I think I remember writing that error message. :-)

Thanks for the response. I've submitted a trivial PR to add the renaming trick to the help page.

**Comment by MalEbenSo** [comment]
Steve, thanks for (co-) making Spectre back in the days. Great game fun at the time.

(Sorry everybody for posting off-topic. I did not know how to direct message Steve in Github.)

**Comment by steve-scalyr** [comment]
Thanks! We had a lot of fun writing it.
