### ISSUE TITLE
Apps crashing

### ISSUE THREAD

**Issue by macjeff** [felixrieseberg/macintosh.js#59]
I am trying to run this game (and I also tried a couple others)
https://macintoshgarden.org/games/crystal-quest

I used this to mount it and it works

https://macintoshgarden.org/apps/virtual-dvd-romcd-utility

But when I run it, the app freezes.  Tried this with a couple other games and utilities and the same issue.

**Comment by MikePlus** [comment]
I'm having the same issue with Crystal Quest. The whole macintosh.js.app just freezes.
