### ISSUE TITLE
Image Files higher than 2GB won´t work

### ISSUE THREAD

**Issue by PeterStrick** [felixrieseberg/macintosh.js#61]
Disk and Image Files that are higher than 2GB will crash Macintosh.js

The following Disk Image Sizes work and were tested:

100MB Disk Image (HFS)- source: https://www.macintoshrepository.org/1922-blank-hard-drive-disk-images-100mb-hfs-up-to-30gb-hfs- 
1GB Disk Image (Blank) - created on WIndows using command: fsutil file createnew 1gb.dsk 1056964608
1GB Disk Image (DOS) - source: https://macintoshgarden.org/apps/dos-mounter-95
2GB Disk Image (Blank) - created on WIndows using command: fsutil file createnew 2gb.dsk 2113929216

Disk Images larger than 2gb, created using fsutil or downloaded from the Macintosh Repository or Macintosh Garden didn´t work and gave the following error message in the developer tools console: 
![image](https://user-images.githubusercontent.com/60312421/89324229-3e289f00-d687-11ea-9f48-18f8cf9ed2c0.png)

**Comment by felixrieseberg** [comment]
That sounds right, because we'll keep all of this in memory. Maybe use the "real" Basilisk II?

http://basilisk.cebix.net/
