### ISSUE TITLE
App starts. but the screen of the app is black.

### ISSUE THREAD

**Issue by timelifexyz** [felixrieseberg/macintosh.js#76]
Hello!

I have issues with the App itself. when i try to start it its just a black screen.

Does someone have a solution for that?

My Laptops Specs:
Intel HD Graphics
2x Intel Celeron
HGST HTS725050A7E630 (404 GB Hard Drive)
PnP Monitor (Standard)

**Comment by jeanpat** [comment]
Same problem on the third use (ubuntu 18.04)

- first time: boot fine + install an app
- second time: boot fine + use the app

- install some stuff: nodejs

third time: boot stucked near the end :
![Capture du 2020-10-09 15-32-04](https://user-images.githubusercontent.com/693574/95589508-21bd3000-0a45-11eb-8dab-1fe7e75dcc4d.png)
Unstall nodejs, remove the .macintosh.js directory, desinstall+reinstall the deb file

still stucked on boot

**Comment by timelifexyz** [comment]
What do you mean?

> Same problem on the third use (ubuntu 18.04)
> 
> * first time: boot fine + install an app
> * second time: boot fine + use the app
> * install some stuff: nodejs
> 
> third time: boot stucked near the end :
> ![Capture du 2020-10-09 15-32-04](https://user-images.githubusercontent.com/693574/95589508-21bd3000-0a45-11eb-8dab-1fe7e75dcc4d.png)
> Unstall nodejs, remove the hidden .macintosh.js directory, desinstall+reinstall the deb file
> 
> still stucked on boot
> 
> Finally: remove the content of ~/macintosh.js (there was a compress app and a symlink to a directory)
> Restart: this time macintosh.js boots fine

**Comment by timelifexyz** [comment]
I will make another because this is probaly OOD
